name: PHP CI for Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, intl, mysql, pdo, pdo_mysql
        ini-values: post_max_size=256M, upload_max_filesize=256M

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Set up test environment
      run: |
        cp .env.example .env
        php artisan key:generate

    - name: Run DatabaseConnectionTest
      run: ./vendor/bin/phpunit --filter DatabaseConnectionTest includes/tests/DatabaseConnectionTest.php

    - name: Run ForgotPasswordTest
      run: ./vendor/bin/phpunit --filter ForgotPasswordTest includes/tests/ForgotPasswordTest.php

    - name: Run NewsletterSubscriptionTest
      run: ./vendor/bin/phpunit --filter NewsletterSubscriptionTest includes/tests/NewsletterSubscriptionTest.php

    - name: Send success notification
      if: success()
      run: echo "✅ All tests passed successfully!"

    - name: Send failure notification
      if: failure()
      run: echo "❌ Some tests failed. Check the logs for details."

    - name: Upload test report
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: storage/logs/test-report.log
