name: CI/CD Pipeline with PHPUnit Tests and Deployment

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  phpunit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo, pdo_mysql

      - name: Download PHPUnit
        run: |
          wget -O phpunit https://phar.phpunit.de/phpunit-9.phar
          chmod +x phpunit
          sudo mv phpunit /usr/local/bin/phpunit

      - name: Run PHPUnit tests
        run: phpunit tests > test-results.txt

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: phpunit-test-results
          path: test-results.txt

      - name: Notify Test Results
        if: success() || failure()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "All tests passed successfully!";
          else
            echo "One or more tests failed. Please check the test results.";
          fi

  deploy:
    needs: phpunit-tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH for Deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh $SERVER_USER@$SERVER_IP << 'EOF'
            cd /path/to/deployment
            git pull origin main
            php artisan migrate
          EOF

      - name: Notify Deployment Success
        if: success()
        run: echo "Deployment successful!"

      - name: Notify Deployment Failure
        if: failure()
        run: echo "Deployment failed. Check logs for details."
