name: CI/CD Pipeline with PHPUnit Tests and Deployment

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  phpunit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo, pdo_mysql

      - name: Download PHPUnit
        run: |
          wget -O phpunit https://phar.phpunit.de/phpunit-9.phar
          chmod +x phpunit
          sudo mv phpunit /usr/local/bin/phpunit

      - name: Run PHPUnit tests
        run: phpunit tests > test-results.txt

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: phpunit-test-results
          path: test-results.txt

      - name: Notify Test Results
        if: success() || failure()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "All tests passed successfully!";
          else
            echo "One or more tests failed. Please check the test results.";
          fi

  deploy:
    needs: phpunit-tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH for Deployment
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_KEY" > private_key.pem
          chmod 600 private_key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        env:
          SERVER: ${{ secrets.SERVER_IP }}
          USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh -i private_key.pem $USER@$SERVER "cd /path/to/deployment && git pull origin main && php artisan migrate"

      - name: Notify Deployment Status
        if: success()
        run: echo "Deployment successful!"
        
      - name: Notify Deployment Failure
        if: failure()
        run: echo "Deployment failed. Check logs for details."
