name: PHP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  php:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # Specify the PHP version you want to use
        extensions: mbstring, intl  # List any necessary PHP extensions

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit --configuration phpunit.xml --testsuite tests  # Run PHPUnit tests from the tests folder

    - name: Check code style (optional)
      run: vendor/bin/phpcs --standard=PSR12 src  # Assuming you use PHP_CodeSniffer for code style checking
